name: Apply clang-tidy fixes

on:
  push: { }
  pull_request: { }
  workflow_dispatch: { }

jobs:
  clang-tidy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Setup
        run: |
          sudo apt update
          sudo apt install -y clang-tidy ninja-build

      - name: Running clang-tidy
        run: |
          cmake -S . -B ./build -G Ninja -DRKE_USE_CLANG_TIDY=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          cmake --build ./build -j 1 -v

      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: clang-tidy-fixes-${{ github.ref }}
          base: ${{ github.head_ref }}
          delete-branch: true
          commit-message: "Automated fixes by clang-tidy"
          title: "Automated fixes by clang-tidy"
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          body: |
            This is an automated PR generated by the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.
            Please review the changes before merging.
